version: '3'
services:
  app:
    container_name: app
    image: node:19-alpine
    working_dir: /app
    command: sh -c 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    environment: 
      TZ: 'Asia/Tokyo'
    tty: true
    restart: always